# This file contains values from Cookiecutter

default_context:
  project_name: "featurebyte"
  project_description: "Python Library for FeatureOps"
  organization: "FeatureByte"
  license: "Apache Software License 2.0"
  minimal_python_version: 3.7
  github_name: "featurebyte"
  email: "it-admin@featurebyte.com"
  version: "0.1.0"
  line_length: "100"
  create_example_template: "cli"
